src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/controller/UserController.java

+ Add pathvariable in meetingcontroller
+ Add import in usercontroller
close #13

[Nexters/www-be#13] Fix project setup in controller

---

src/main/java/com/promise8/wwwbe/WwwBeApplication.java
src/main/java/com/promise8/wwwbe/model/entity/BaseTimeEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingPlaceEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingUserEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingUserTimetableEntity.java
src/main/java/com/promise8/wwwbe/model/entity/PlaceVoteEntity.java
src/main/java/com/promise8/wwwbe/model/entity/UserEntity.java

Add created and updated datetime
close #17

[Nexters/www-be#17] Add created and updated datetime

---

src/main/resources/application-alpha.yml

[Nexters/www-be#3] alpha setup

[Nexters/www-be#3] alpha setup

---

.github/workflows/maven.yml
src/test/java/com/promise8/wwwbe/repository/UserRepositoryTest.java

Add github actions for maven build test
close #14

[Nexters/www-be#14] Add Maven build test

---

.github/workflows/slack.yml

add slack and github connection for push notification
close #22

[Nexters/www-be#22] Add slack and github connect

---

src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java

[Nexters/www-be#20]
+ Delete voteEndDate
+ Fix column name userId -> hostId
+ Add meetingCode

[Nexters/www-be#20] Fix Entities

---

.github/workflows/maven.yml
.github/workflows/slack.yml

Fix branch name to applying workflows
+ main -> master
close #21

[Nexters/www-be#21] Fix branch name to applying workflows

---

src/main/java/com/promise8/wwwbe/model/entity/UserEntity.java

[Nexters/www-be#20] Delete uuid in userEntity

[Nexters/www-be#20] Delete uuid in userEntity

---

pom.xml
src/main/java/com/promise8/wwwbe/config/security/CustomUserDetailsService.java
src/main/java/com/promise8/wwwbe/config/security/DeviceIdAuthenticationProvider.java
src/main/java/com/promise8/wwwbe/config/security/SecurityConfig.java
src/main/java/com/promise8/wwwbe/config/security/TokenAuthenticationFilter.java
src/main/java/com/promise8/wwwbe/config/security/TokenProvider.java
src/main/java/com/promise8/wwwbe/config/security/UserPrincipal.java
src/main/java/com/promise8/wwwbe/controller/UserController.java
src/main/java/com/promise8/wwwbe/model/dto/LoginReqDto.java
src/main/java/com/promise8/wwwbe/model/entity/UserEntity.java
src/main/resources/application-local.yml
src/test/java/com/promise8/wwwbe/config/security/TokenProviderTest.java

[Nexters/www-be#5] user join API 
- spring security tokenAuthenticationFilter 추가
- deviceId 기반 토큰 발급 및 인증 구현

[Nexters/www-be#5] user join API

---

pom.xml
src/main/java/com/promise8/wwwbe/config/FirebaseConfig.java
src/main/java/com/promise8/wwwbe/config/FirebaseProperties.java
src/main/java/com/promise8/wwwbe/config/security/DeviceIdAuthenticationProvider.java
src/main/java/com/promise8/wwwbe/controller/GlobalExceptionHandler.java
src/main/java/com/promise8/wwwbe/controller/UserController.java
src/main/java/com/promise8/wwwbe/model/dto/LoginReqDto.java
src/main/java/com/promise8/wwwbe/model/entity/UserEntity.java
src/main/java/com/promise8/wwwbe/model/exception/BizException.java
src/main/java/com/promise8/wwwbe/model/http/BaseErrorCode.java
src/main/java/com/promise8/wwwbe/model/http/BaseResponse.java
src/main/java/com/promise8/wwwbe/service/PushService.java
src/main/resources/application.yml
src/main/resources/firebase-service-account.json
src/test/java/com/promise8/wwwbe/service/PushServiceTest.java

[Nexters/www-be#11] firebase push notification 적용 
- 앱쪽 sdk 적용 이후에 확인 필요
- response, errcode 등 메소드 추가, 필드명 변경

[Nexters/www-be#11] firebase push notification 적용

---

pom.xml
src/main/java/com/promise8/wwwbe/config/security/SecurityConfig.java
src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/model/dto/DynamicLinkReqDto.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingCreateReqDto.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingCreateResDto.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingGetRes.java
src/main/java/com/promise8/wwwbe/model/dto/PromiseDateAndTimeDto.java
src/main/java/com/promise8/wwwbe/model/dto/PromiseTime.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingPlaceEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingUserEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingUserTimetableEntity.java
src/main/java/com/promise8/wwwbe/model/entity/PlaceVoteEntity.java
src/main/java/com/promise8/wwwbe/model/entity/UserEntity.java
src/main/java/com/promise8/wwwbe/repository/MeetingRepository.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/resources/application-alpha.yml
src/main/resources/application-local.yml

[Nexters/www-be#6]
+ createMeeting api를 추가한다.
+ link, device 식별을 위한 로직은 이후 추가할 예정
+ SecurityConfig의 `/meetings` 요청의 접근을 허용한다.
+ `RandomStringUtils` 사용을 위한 의존성을 추가한다.

[Nexters/www-be#6] Add createMeeting api

---

src/main/java/com/promise8/wwwbe/config/SwaggerConfig.java
src/main/java/com/promise8/wwwbe/config/security/UserPrincipal.java
src/main/java/com/promise8/wwwbe/controller/PushTestController.java
src/main/java/com/promise8/wwwbe/model/mobile/PushMessage.java
src/main/java/com/promise8/wwwbe/service/PushService.java
src/test/java/com/promise8/wwwbe/service/IntegrationPushServiceTest.java
src/test/java/com/promise8/wwwbe/service/PushServiceTest.java

[nexters/www-be#noissue] push test용 controller 추가

[nexters/www-be#noissue] push test용 controller 추가

---

src/main/java/com/promise8/wwwbe/config/SwaggerConfig.java
src/main/java/com/promise8/wwwbe/config/security/SecurityConfig.java
src/main/java/com/promise8/wwwbe/config/security/TokenAuthenticationFilter.java

+ 인증이 안된 상태에서 통과되는 부분을 수정한다.
+ 경로 /meetings을 인증을 거치도록 변경한다.
+ Swagger에 authorization을 추가한다.
- close #35

[Nexters/www-be#35] Add authorization in swagger

---

src/main/java/com/promise8/wwwbe/model/dto/MeetingCreateReqDto.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingGetRes.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingStatus.java
src/main/java/com/promise8/wwwbe/model/dto/UserVoteResDto.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingUserEntity.java
src/main/java/com/promise8/wwwbe/model/entity/PlaceVoteEntity.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java

+ Add meetingStatus in MeetingEntity
+ Fix UserEntity -> MeetingUserEntity
- close #34

[Nexters/www-be#34] Fix Entities

---

src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingMainGetResDto.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingMainGetResDtoWrapper.java
src/main/java/com/promise8/wwwbe/model/dto/UserPromiseTimeResDto.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingPlaceEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingUserTimetableEntity.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/test/java/com/promise8/wwwbe/repository/MeetingRepositoryTest.java

[Nexters/www-be#6]
+ getMeetingList api를 추가한다.
+ MeetingRepositoryTest를 추가한다.
+ 변수 isConfirmed를 추가한다.
+ MeetingUserTimetableEntity
+ MeetingPlaceEntity
- close #42

[Nexters/www-be#6] Add getMeetingList

---

src/main/java/com/promise8/wwwbe/model/dto/MeetingMainGetResDtoWrapper.java

[Nexters/www-be#6] Fix Enum compare

---

src/main/java/com/promise8/wwwbe/config/RestTemplateConfig.java
src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/model/dto/DynamicLinkResDto.java
src/main/java/com/promise8/wwwbe/service/LinkService.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/test/java/com/promise8/wwwbe/service/LinkServiceTest.java

[nexters/www-be#31] LinkService refactoring

[nexters/www-be#noissue] LinkService refactoring

---

src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingCreateReqDto.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingGetResDto.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java

+ getMeeting에 isHost, shortLink 추가
+ MeetingEntity에 shortLink 추가
+ isHost를 위해 header의 유저 정보 활용
- close #50

[Nexters/www-be#50] Add isHost, dynamicLink

---

src/main/java/com/promise8/wwwbe/model/dto/MeetingMainGetResDtoWrapper.java
src/main/java/com/promise8/wwwbe/model/dto/PromiseTime.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingStatus.java

+ enum에 priority 추가
+ MeetingStatus
+ PromiseTime
+ getMeetingList sorting 방식 일부를 ordinal에서 priority로 변경
+ close #51

[Nexters/www-be#51] Add priority in enums

---

pom.xml
src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/model/dto/ConfirmedPromiseDto.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingCreateReqDto.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingGetResDto.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingMainGetResDto.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
src/test/java/com/promise8/wwwbe/service/MeetingServiceTest.java

+ MockedStatic 사용을 위한 의존성 추가
+ MeetingService에 대한 Test Methods 추가
+ 테스트 진행 과정에서 발생한 예외 처리
+ createMeeting api에 UserPrincipal 추가
+ UserPrincipal에서 deviceId를 가져오도록 수정
+ deviceId는 MeetingCreateReq에서 제외

[Nexters/www-be#noissue] Add MeetingServiceTest

---

src/main/java/com/promise8/wwwbe/service/MeetingService.java

+ createMeeting 시 userName을 갱신하는 로직 추가

[Nexters/www-be#noissue] Fix update userName at create meeting

---

pom.xml
src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/model/dto/ConfirmedPromiseDto.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingCreateReqDto.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingGetResDto.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingMainGetResDto.java
src/main/java/com/promise8/wwwbe/repository/MeetingUserRepository.java
src/main/java/com/promise8/wwwbe/service/MeetingAuthorizer.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
src/test/java/com/promise8/wwwbe/service/MeetingServiceTest.java

getMeetingById api에 본인 확인 로직 추가

[Nexters/www-be#noissue] Add PreAuthorize getMeetingById api

---

src/main/java/com/promise8/wwwbe/WwwBeApplication.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingPlaceEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingUserEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingUserTimetableEntity.java
src/main/java/com/promise8/wwwbe/model/entity/PlaceVoteEntity.java
src/main/java/com/promise8/wwwbe/model/entity/UserEntity.java
src/main/java/com/promise8/wwwbe/repository/MeetingRepository.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java

+ 매일 0시 0분 2초마다 업데이트 진행
+ `CONFIRMED` 상태, `promiseDate`가 하루 이상 지난 약속 방을 `DONE` 상태로 변경한다.
- close #56

[Nexters/www-be#56] Add Scheduler for change MeetingStatus

---

src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/model/dto/PlaceVoteReqDto.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingPlaceEntity.java
src/main/java/com/promise8/wwwbe/repository/MeetingPlaceRepository.java
src/main/java/com/promise8/wwwbe/repository/MeetingUserRepository.java
src/main/java/com/promise8/wwwbe/repository/PlaceVoteRepository.java
src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java

[nexters/www-be#9] vote place list

[nexters/www-be#9] vote place list

---

src/test/java/com/promise8/wwwbe/repository/MeetingRepositoryTest.java

findByMeetingStatusAndConfirmedDate 메소드 테스트 코드 추가

[Nexters/www-be#noissue] Add meetingRepo test

---

src/main/java/com/promise8/wwwbe/controller/UserController.java
src/main/java/com/promise8/wwwbe/model/dto/AlarmReqDto.java
src/main/java/com/promise8/wwwbe/model/entity/UserEntity.java
src/main/java/com/promise8/wwwbe/service/UserService.java
src/test/java/com/promise8/wwwbe/service/UserServiceTest.java

[nexters/www-be#noissue] alarm setup

[nexters/www-be#noissue] alarm setup

---

src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/model/dto/JoinMeetingReqDto.java
src/main/java/com/promise8/wwwbe/model/dto/UserPromiseTimeReqDto.java
src/main/java/com/promise8/wwwbe/model/http/BaseErrorCode.java
src/main/java/com/promise8/wwwbe/repository/MeetingUserTimetableRepository.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/test/java/com/promise8/wwwbe/repository/UserRepositoryTest.java
src/test/java/com/promise8/wwwbe/service/integration/MeetingServiceIntegrationTest.java

[nexters/www-be#10] join meeting API

[nexters/www-be#10] join meeting API

---

src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingGetResDto.java
src/main/java/com/promise8/wwwbe/model/http/BaseErrorCode.java
src/main/java/com/promise8/wwwbe/service/MeetingAuthorizer.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/test/java/com/promise8/wwwbe/service/MeetingServiceTest.java

+ getMeeting에서 이미 참여한 유저인지 확인하는 로직 추가
+ 존재하지 않거나 WAITING 상태가 아닌 약속방에 대한 에러 코드 추가
+ getMeetingById에서 @PreAuthorize 제거
- close #63

[Nexters/www-be#63] Add checking isJoined user and meetingStatus

---

src/main/java/com/promise8/wwwbe/config/SwaggerConfig.java

[Nexters/www-be#66] Fix Swagger Request url

---

src/main/java/com/promise8/wwwbe/config/SwaggerConfig.java

실행 중인 profiles active에 맞는 host를 등록한다.
- close #68

[Nexters/www-be#68] Fix Swagger host

---

src/main/java/com/promise8/wwwbe/model/dto/MeetingCreateResDto.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingGetResDto.java
src/main/java/com/promise8/wwwbe/model/dto/MeetingMainGetResDto.java
src/main/java/com/promise8/wwwbe/model/dto/UserPromisePlaceResDto.java
src/main/java/com/promise8/wwwbe/model/dto/UserPromiseTimeResDto.java

+ response dto에 nullable 추가
- close #48

[Nexters/www-be#48] Add nullable responsedto

---

src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/controller/UserController.java
src/main/java/com/promise8/wwwbe/service/UserService.java

+ swagger에 api 설명을 추가한다.
- close #73

[Nexters/www-be#73] Add api description for swagger

---

src/main/java/com/promise8/wwwbe/config/security/CustomUserDetailsService.java
src/main/java/com/promise8/wwwbe/model/http/BaseErrorCode.java
src/main/java/com/promise8/wwwbe/model/mobile/PushMessage.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
src/main/java/com/promise8/wwwbe/service/PushService.java
src/main/java/com/promise8/wwwbe/service/UserService.java
src/test/java/com/promise8/wwwbe/service/IntegrationPushServiceTest.java
src/test/java/com/promise8/wwwbe/service/PushServiceTest.java

[nexters/www-be#noissue] code refactor

[nexters/www-be#noissue] code refactor

---

src/main/java/com/promise8/wwwbe/service/MeetingService.java

약속 방 생성 시 시간, 장소에 `isConfirmed = false`를 추가한다.

[Nexters/www-be#77] Fix isConfirmed at createMeeting

---

src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java
src/main/java/com/promise8/wwwbe/model/dto/res/MeetingMainGetResDtoWrapper.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java

[Nexters/www-be#76]
Refactoring sorting

[Nexters/www-be#76] Refactoring sorting

---

src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java

약속방 상세정보에 `어디서` 투표에 참여한 총 인원 수 추가

[Nexters/www-be#77] Add votingUserCount in MeetingDetail

---

src/main/java/com/promise8/wwwbe/repository/MeetingPlaceRepository.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java

[Nexters/www-be#77] Add solving conflict of place

---

.github/workflows/cicd.yml
infra/Dockerfile

git actions를 이용한 cicd 추가
- close #83

[Nexters/www-be#83] Add Dockerfile and cicd.yml for cicd

---

.github/workflows/cicd.yml

[Nexters/www-be#83] Fix path

---

.github/workflows/cicd.yml

Merge develop to master for deploy.

Merge develop to master

---

infra/Dockerfile

[Nexters/www-be#83] Fix Dockerfile

---

.github/workflows/cicd.yml
infra/Dockerfile

Fix Dockerfile

---

.github/workflows/cicd.yml

[Nexters/www-be#83] Fix cicd rmi

---

.github/workflows/cicd.yml

[Nexters/www-be#83] Fix cicd

---

src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java

[nexters/www-be#noissue] response add

[nexters/www-be#noissue] response add

---

src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/controller/UserController.java
src/main/java/com/promise8/wwwbe/service/MeetingAuthorizer.java
src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java

+ api description을 수정한다.
+ ErrorCode를 수정한다.

[Nexters/www-be#77] Fix swagger docs

---

src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/controller/UserController.java
src/main/java/com/promise8/wwwbe/service/MeetingAuthorizer.java
src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java

* [Nexters/www-be#77] Fix errorCode message for swagger
* [Nexters/www-be#77] Fix getMeeting by code api description

[Nexters/www-be#77] Fix swagger docs (#97)

---

src/main/java/com/promise8/wwwbe/controller/GlobalExceptionHandler.java
src/main/java/com/promise8/wwwbe/service/MeetingAuthorizer.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java

[Nexters/www-be#77] Delete result at BaseResponse error

---

src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/model/exception/BizException.java

[Nexters/www-be#77] Delete no use

---

src/main/java/com/promise8/wwwbe/controller/MeetingUserTimetableController.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
src/main/java/com/promise8/wwwbe/service/MeetingUserTimetableService.java

+ 약속방 내 유저들이 선택한 시간정보 조회 api를 추가한다.
+ 더보기 누를 시 업데이트된 시간 정보를 받야아함

[Nexters/www-be#77] Add getTimetableList

---

src/main/java/com/promise8/wwwbe/controller/MeetingUserTimetableController.java
src/main/java/com/promise8/wwwbe/controller/PlaceVoteController.java
src/main/java/com/promise8/wwwbe/model/dto/res/PromisePlaceResDtoWrapper.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
src/main/java/com/promise8/wwwbe/service/MeetingUserTimetableService.java
src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java

+ 약속방 내 유저들이 투표한 장소정보 조회 api를 추가한다.
+ 더보기 누를 시 업데이트된 투표 정보를 받야아함
+ 본인이 투표한 장소정보도 포함한다.

[Nexters/www-be#77] getPlaceVoteList

---

src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/controller/MeetingUserTimetableController.java
src/main/java/com/promise8/wwwbe/controller/PlaceVoteController.java
src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java
src/main/java/com/promise8/wwwbe/model/dto/res/PromisePlaceResDtoWrapper.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
src/main/java/com/promise8/wwwbe/service/MeetingUserTimetableService.java
src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
src/test/java/com/promise8/wwwbe/service/MeetingServiceTest.java

+ MeetingGetResDto에 이미 참여된 유저들의 닉네임을 추가한다.
+ 유저 join 시 닉네임 중복체크를 위함
+ creator -> currentUser 변경

[Nexters/www-be#77] Add joinedUserList

---

.github/workflows/slack.yml

+ Slack Notification 추가
+ push master

[Nexters/www-be#noissue] Add push master notification

---

src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingStatus.java
src/main/java/com/promise8/wwwbe/model/mobile/PushMessage.java
src/main/java/com/promise8/wwwbe/repository/PlaceVoteRepository.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
src/test/java/com/promise8/wwwbe/repository/PlaceVoteRepositoryTest.java
src/test/java/com/promise8/wwwbe/service/MeetingServiceTest.java
src/test/java/com/promise8/wwwbe/service/integration/MeetingServiceIntegrationTest.java

api 호출에 의한 알림을 추가한다.
+ 예상인원 참가 시
+ 투표 시작 시
+ 투표 종료 시
+ 방장이 투표 종료
+ 모든 참여자의 투표가 종료
- close #92

[Nexters/www-be#92] Add Notification by api

---

src/main/java/com/promise8/wwwbe/config/security/DeviceIdAuthenticationProvider.java

유저 등록 시 `isAlarmOn = true`를 추가한다.

[Nexters/www-be#77] Add init isAlarmOn

---

src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
src/main/java/com/promise8/wwwbe/model/entity/UserEntity.java

+ String으로 select 시 대소문자 구분을 하지않는 문제 해결

[Nexters/www-be#77] Fix select select conflict

---

src/main/java/com/promise8/wwwbe/model/dto/PromiseTime.java
src/main/java/com/promise8/wwwbe/repository/MeetingPlaceRepository.java
src/main/java/com/promise8/wwwbe/repository/MeetingRepository.java
src/main/java/com/promise8/wwwbe/repository/MeetingUserTimetableRepository.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
src/test/java/com/promise8/wwwbe/service/MeetingServiceTest.java

[Nexters/www-be#93]
+ 약속 하루 전 알림 스케줄러 추가
+ 알림 메시지를 위한 PromiseTime에 한글 텍스트 추가
+ 모든 알림에서 알림설정 on인 유저들에게만 전송되도록 수정

[Nexters/www-be#93] Add notification scheduler

---

src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/model/dto/req/MeetingConfirmDto.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
src/main/java/com/promise8/wwwbe/model/http/BaseErrorCode.java
src/main/java/com/promise8/wwwbe/repository/MeetingRepository.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/test/java/com/promise8/wwwbe/service/integration/MeetingServiceIntegrationTest.java

[nexters/www-be#noissue] 약속 확정 API, 약속 확정 재촉 노티

[nexters/www-be#noissue] 약속 확정 API, 약속 확정 재촉 노티

---

src/main/java/com/promise8/wwwbe/model/dto/UserInfoDto.java
src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java
src/main/java/com/promise8/wwwbe/model/dto/res/MeetingMainGetResDto.java
src/main/java/com/promise8/wwwbe/model/dto/res/UserPromisePlaceResDto.java
src/main/java/com/promise8/wwwbe/model/dto/res/UserPromiseTimeResDto.java
src/main/java/com/promise8/wwwbe/service/LinkService.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
src/main/java/com/promise8/wwwbe/service/ThumbnailHelper.java

[nexters/www-be#noissue] refactoring chracter

[nexters/www-be#noissue] refactoring chracter

---

src/main/java/com/promise8/wwwbe/model/dto/UserInfoDto.java
src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java
src/main/java/com/promise8/wwwbe/model/dto/res/MeetingMainGetResDto.java
src/main/java/com/promise8/wwwbe/model/dto/res/UserPromisePlaceResDto.java
src/main/java/com/promise8/wwwbe/model/dto/res/UserPromiseTimeResDto.java
src/main/java/com/promise8/wwwbe/service/LinkService.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
src/main/java/com/promise8/wwwbe/service/ThumbnailHelper.java

* [nexters/www-be#noissue] refactoring chracter
* [nexters/www-be#noissue] bug fix

[nexters/www-be#noissue] refactoring chracter (#113)

---

src/main/java/com/promise8/wwwbe/model/dto/PromiseTime.java

promiseTime `LUNCH` 점심 -> 낮으로 변경

[Nexters/www-be#77] Fix promiseTime naming

---

src/main/java/com/promise8/wwwbe/config/security/DeviceIdAuthenticationProvider.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java

+ 앱 로딩 시마다 fcmToken 갱신 추가
+ 추가적인 버그 수정

[Nexters/www-be#77] Fix bugs

---

src/main/java/com/promise8/wwwbe/model/dto/res/UserPromisePlaceResDto.java
src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java

+ 유저 프로필 사진에 사용할 id를 meetingUserId로 변경한다.
+ 방 내에서 보여질 userName을 meetingUserName으로 변경한다.

[Nexters/www-be#77] Fix CharacterType userId -> meetingUserId

---

src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java

+ 약속방 내에 보이는 userName을 meetingUserName으로 변경
+ CharacterType을 userEntity.userId로 변경

[Nexters/www-be#77] Fix meetingDetail userName

---

src/main/java/com/promise8/wwwbe/model/dto/res/UserPromisePlaceResDto.java
src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
src/main/java/com/promise8/wwwbe/service/ThumbnailHelper.java

[Nexters/www-be#77] Fix CharacterType host

---

src/main/java/com/promise8/wwwbe/service/PushService.java

+ pushMessageHistory를 save한 이후에 setId 메소드를 수행하도록 순서를 변경한다.

[Nexters/www-be#77] Fix pushMsgHistoryId

---

src/main/java/com/promise8/wwwbe/model/dto/res/UserPromisePlaceResDto.java
src/main/java/com/promise8/wwwbe/model/dto/res/UserPromiseTimeResDto.java
src/main/java/com/promise8/wwwbe/repository/MeetingPlaceRepository.java
src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java

+ Jpa의 delete 메소드를 사용하는 Service 레벨 메소드에 @Transactional을 추가한다.
+ 투표 시 MeetingPlaceEntity를 MeetingUser와 PlaceList 기준으로 찾는 로직을 PlaceList만으로 찾도록 변경한다.
+ timetable, place id를 res에 추가한다.

[Nexters/www-be#77] Add vote method

---

src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java
src/test/java/com/promise8/wwwbe/service/MeetingServiceTest.java

[Nexters/www-be#77] delete calling notification

---

src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingPlaceEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingUserEntity.java
src/main/java/com/promise8/wwwbe/model/entity/MeetingUserTimetableEntity.java
src/main/java/com/promise8/wwwbe/model/entity/PlaceVoteEntity.java
src/main/java/com/promise8/wwwbe/model/entity/PushMessageHistoryEntity.java
src/main/java/com/promise8/wwwbe/model/entity/UserEntity.java

+ currentUserName을 userEntity에서 meetingUserEntity의 name으로 변경
+ Entity들의 Id type을 Long 객체로 변경

[Nexters/www-be#77] Fix currentUserName to meetingUserName

---

src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/test/java/com/promise8/wwwbe/service/integration/MeetingServiceIntegrationTest.java

[nexters/www-be#77] meeting status fix

[nexters/www-be#77] meeting status fix

---

src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java
src/main/java/com/promise8/wwwbe/model/dto/res/MeetingMainGetResDto.java

+ MeetingDetails에 yaksokiType 추가

[Nexters/www-be#77] Add MeetingDetails yaksokiType

---

src/main/java/com/promise8/wwwbe/controller/MeetingController.java
src/main/java/com/promise8/wwwbe/model/http/BaseErrorCode.java
src/main/java/com/promise8/wwwbe/service/MeetingAuthorizer.java

+ VOTING 상태가 아닌 약속방에서 투표요청 시 에러 추가

[Nexters/www-be#77] Add voting status check

---

src/main/java/com/promise8/wwwbe/model/dto/res/UserPromisePlaceResDto.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/test/java/com/promise8/wwwbe/repository/MeetingRepositoryTest.java

[Nexters/www-be#77] Add place sorting

---

src/main/java/com/promise8/wwwbe/controller/MeetingPlaceController.java
src/main/java/com/promise8/wwwbe/service/MeetingPlaceService.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java

+ MeetingPlace api를 추가한다.
+ 현재 방의 meetingPlaceList를 받아오는 api 추가

[Nexters/www-be#77] Add MeetingPlace api

---

src/main/java/com/promise8/wwwbe/controller/MeetingPlaceController.java
src/main/java/com/promise8/wwwbe/model/dto/res/MeetingGetResDto.java
src/main/java/com/promise8/wwwbe/model/dto/res/MeetingMainGetResDto.java
src/main/java/com/promise8/wwwbe/model/dto/res/UserPromisePlaceResDto.java
src/main/java/com/promise8/wwwbe/service/MeetingPlaceService.java
src/main/java/com/promise8/wwwbe/service/MeetingService.java
src/main/java/com/promise8/wwwbe/service/MeetingServiceHelper.java
src/test/java/com/promise8/wwwbe/repository/MeetingRepositoryTest.java

+ meeting main, detail에 confirmedDayOfWeek 추가

[Nexters/www-be#77] Add confirmedDayOfWeek

---

src/main/java/com/promise8/wwwbe/model/dto/res/PromisePlaceResDtoWrapper.java
src/main/java/com/promise8/wwwbe/service/PlaceVoteService.java

[nexters/www-be#77] voted user count

[nexters/www-be#77] voted user count
